### ISSUE TITLE
AudioFileOpen failed on macOS Catalina

### ISSUE THREAD

**Issue by bhrutledge** [rhpvorderman/pytest-notification#4]
Thanks for making this! Sadly, it looks like `afplay` isn't working on macOS Catalina:

```
$ pytest --sound
============================= test session starts ==============================
platform darwin -- Python 3.8.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /Users/brian/Code/pytest-quarantine
plugins: notification-0.1.0, quarantine-2.0.0
collected 17 items

tests/test_quarantine.py .................                               [100%]

======================= 17 passed, 11 warnings in 0.96s ========================
Error: AudioFileOpen failed ('typ?')
```

Trying to play `DEFAULT_FAIL_SOUND` directly:

```
$ afplay ./venv/lib/python3.8/site-packages/pytest_notification/sounds/buzzer.oga
Error: AudioFileOpen failed ('typ?')
```

**Comment by rhpvorderman** [comment]
Oh shoot. It does not love the free ogg audio format.
I have no mac, so I cannot debug.
What happens if you rename the `buzzer.oga` file to `buzzer.ogg`?

**Comment by bhrutledge** [comment]
No luck. Same error.

**Comment by rhpvorderman** [comment]
Hmm. Okay. 
I have been hesitant at providing an mp3 file, because these used to require a license. However I see now that all patents regarding mp3 encoding [have expired](https://www.iis.fraunhofer.de/en/ff/amm/consumer-electronics/mp3.html). 

Unfortunately mp3 is not supported the `paplay` command in linux. 

Maybe I can add both an mp3 and an ogg file so it will work on Mac OS X as well.

I will look into it.

**Comment by rhpvorderman** [comment]
Hi @bhrutledge,

I have been making some changes and added an mp3 file as well. 
Could you try `pip install git+https://github.com/rhpvorderman/pytest-notification.git@sounds` and check out if that works on your mac?
